### ISSUE TITLE
[BUG]Traceback seems not able to print locals nor code around

### ISSUE THREAD

**Issue by timsu92** [willmcgugan/rich#864]
**Describe the bug**
In readme, the [screenshot](https://github.com/willmcgugan/rich#tracebacks) shows it's able to show local variables and code around while printing exceptions. However, this is what I see:
![image](https://user-images.githubusercontent.com/33785401/103347429-f7be5b80-4ad1-11eb-9ba2-0d5b0e82effa.png)

**To Reproduce**
A minimal code example that reproduces the problem would be a big help if you can provide it. If the issue is visual in nature, consider posting a screenshot.
![image](https://user-images.githubusercontent.com/33785401/103348025-b929a080-4ad3-11eb-8a72-e2eb4d67f29c.png)

**Platform**
- OS: Windows 10 20H2 x64
- Rich: 9.4.0 installed by conda 4.9.2 from conda-forge
- IDE: PyCharm community 2020.2.4
- Terminal 1: the one built-in in PyCharm
- Terminal 2: Windows Terminal 1.4.3243.0 ([the new one](https://www.microsoft.com/zh-tw/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab))

**Comment by willmcgugan** [comment]
When you enter code directly in to the REPL it isn't stored on disk, so Rich isn't able to load and display the code in the traceback. If you try it without the Rich handler you can see that the default exception handler doesn't give you a preview either.

I'm afraid I can't do much about the code preview, but Rich should still be able to show the locals. I'll look in to that.

**Comment by timsu92** [comment]
The screenshot is just coping the code to Windows Terminal. If I just run it in PyCharm, the result is almost the same, just the color slightly different.

**Comment by willmcgugan** [comment]
pyCharm has some know problems. See the note here... https://rich.readthedocs.io/en/latest/introduction.html

**Comment by timsu92** [comment]
Yeah, I've noticed that! Thanks!
So~there's only "slightly" difference~

**Comment by timsu92** [comment]
Another thing is: my Rich is in 9.4.0, and Conda blocks me from updating. Would that be the problem?

**Comment by willmcgugan** [comment]
9.5.1 seems to be stuck in [Conda forge](https://github.com/conda-forge/rich-feedstock/pull/42). I'm sure @jan-janssen will be able to resolve it when he has the chance to look at it.

**Comment by willmcgugan** [comment]
Fixed in 9.6.0 (just released)

**Comment by timsu92** [comment]
Wow! Thanks a lot!

**Comment by timsu92** [comment]
### Weird! I still can't see it! Am I getting something wrong?
#### Rendered
![image](https://user-images.githubusercontent.com/33785401/103414867-a6d66200-4bba-11eb-8964-82fe07c47f96.png)
#### Original Python ( comment the first two lines)
![image](https://user-images.githubusercontent.com/33785401/103414890-c40b3080-4bba-11eb-99c2-aa9c2f7fe072.png)
And... by viewing these, Python can get the code!
I've upgraded Rich to 9.6.0 by Conde throough conda-forge, and I've restarted PyCharm.

**Comment by willmcgugan** [comment]
I think there was an encoding error on Windows. Please try v9.6.1

Out of interest can you paste the output of this command:

```
python -m rich.diagnose
```

**Comment by timsu92** [comment]
Yeah! Fixed in 9.6.1! Nice work on the first day in a new year!

As to `python -m rich.diagnose`, here it is:
#### Windows Terminal
 ![image](https://user-images.githubusercontent.com/33785401/103432424-8db0ce00-4c19-11eb-86ec-ae97607895ac.png)
#### The terminal in PyCharm
![image](https://user-images.githubusercontent.com/33785401/103432440-b042e700-4c19-11eb-9b3b-8b77ac73a8e2.png)
#### The normal output of PyCharm
How to do that?🤔

p.s. Now I know why the color is slightly different. PyCharm supports the legacy.
